# Generated by Django 5.2.13 on 2026-07-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('DELIVERY', 'delivery'), ('ADMIN', 'admin'), ('CUSTOMER', 'customer')], max_length=100),
        ),
    ]
