# Generated by Django 5.2.15 on 2026-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'placed'), ('PACKING', 'packing'), ('OUT', 'out for delivery'), ('DELIVERED', 'delivered'), ('CANCELLED', 'cancelled')], default='PLACED', max_length=100),
        ),
    ]
