# Generated by Django 5.2.15 on 2026-09-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fooditem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='image',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
